version: '3.7'

  inventree:
    image: zeigren/inventree:latest
    container_name: inventree
    depends_on:
      - mariadb
    networks:
      - inventree
      - mariadb
    volumes:
      - static:/usr/src/static
      - media:/usr/src/media
    environment:
      # RUN MIGRATE_STATIC WHENEVER YOU UPDATE THE INVENTREE CONTAINER TO A NEW VERSION
      - MIGRATE_STATIC=False
      - DATABASE_NAME=inventree
      - DATABASE_USER=inventree
      - DATABASE_PASSWORD=CHANGEME
      # CREATE SUPERUSER ONCE THEN DELETE THESE
      - CREATE_SUPERUSER=False
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.com
      - DJANGO_SUPERUSER_PASSWORD=admin

networks:
  inventree:

volumes:
  static:
  media:
